### PR TITLE
Updated README Issue 88 and Toolchain Issue 80

### PR DESCRIPTION
**Pull request by JPautz**
Updated files to reflect current technologies being used.

### CODE REVIEW

**Comment by JPautz** [comment]
You can see the file changes here
https://github.com/cpe308-309/AvengersRepo/pull/89/files

**Comment by BryceV** [comment]
Looks solid

**Comment by JPautz** [comment]
Needs to be merged

**Comment by JPautz** [comment]
Is it not accepting your review?

**Comment by JPautz** [comment]
Mission Accomplished

**Pull request merged**
